FROM alpine:latest

RUN apk --no-cache add \
    bash \
    git \
    jq \
    ghostscript \
    graphviz \
    py-pygments \
    python2 \
    python3 \
    py3-pip \
    texlive-full

RUN pip3 install yq
