name: Check regression
on: 
  push:
    branches:
      master

jobs:
  publish:
    name: Check build regression
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build all documents
      uses: ./.github/actions/hse-tex-build
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Documents
        path: .pdf/**/*.pdf